server:
  address: ":8080"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level: "all"
  stdout: true

database:
  default:
    link: "postgres://postgres:postgres@localhost:5432/billionmail?sslmode=disable"
    debug: true

redis:
  default:
    address: "localhost:6379"
    db: 0