server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level: "all"
  stdout: true

database:
  default:
    link: "postgres://billionmail:dev_password_123@pgsql-billionmail:5432/billionmail?sslmode=disable"
    debug: true

redis:
  default:
    address: "redis-billionmail:6379"
    db: 0